### ISSUE TITLE
a small issue

### ISSUE THREAD

**Issue by bettercalldelta** [VoTheHandsome/WebbBot#2]
the issue in question: i'm in your walls vo.

**Comment by VoTheHandsome** [comment]
It is a feature. My walls are not sufficient for a healthy life

**Comment by bettercalldelta** [comment]
Ok

**Comment by bettercalldelta** [comment]
Ok

**Comment by VoTheHandsome** [comment]
https://tenor.com/view/better-call-saul-saul-goodman-saul-ok-gif-22735393

**Comment by VoTheHandsome** [comment]
rare ukrainian road development

**Comment by VoTheHandsome** [comment]
https://tenor.com/view/better-call-saul-saul-goodman-saul-ok-gif-22735393

**Comment by bettercalldelta** [comment]
"Man if only I had a zip bomb that is 12 353 653 155 963 782 858 428 671 064 387 042 666 598 916 611 580 939 841 119 467 653 041 402 561 523 153 496 823 753 888 027 168 243 114 445 670 429 492 914 513 538 130 943 957 121 390 808 923 336 226 715 693 451 991 227 817 771 079 374 200 911 992 994 161 452 622 538 969 283 756 626 099 089 564 495 403 968 390 097 390 695 773 702 442 020 050 803 147 555 684 412 513 136 627 351 818 013 153 603 882 218 219 464 583 806 976 bytes when uncompressed"
https://github.com/bettercalldelta/compression-bombs/blob/main/hypernova.7z :

**Comment by bettercalldelta** [comment]
*funny angel flying gif*

**Comment by VoTheHandsome** [comment]
if only I had windows security which would try to send this zip to ms headquarters and blow them the fuck up

**Comment by bettercalldelta** [comment]
"if only Kalynivka, Dalekolis'ka Hromada, Linvil's'kyi Raion, Linvil's'ka Oblast had roads that look better than the ones in Leanville City"
: 
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/22b33f13-9590-4621-a689-519ecd95ec9a)

**Comment by VoTheHandsome** [comment]
how the fuck are these roads so good

**Comment by VoTheHandsome** [comment]
*cries about it*

**Comment by bettercalldelta** [comment]
it's funny that Farwood, a town that was absolutely torn by war during a siege, now has better roads than Leanville City. about this, may you cry

**Comment by bettercalldelta** [comment]
closed because i got out of your walls

**Comment by VoTheHandsome** [comment]
LITERALLY 1984

**Comment by VoTheHandsome** [comment]
*cries about it 2 times*

**Comment by bettercalldelta** [comment]
"man if only there was a very sad piece of Farwood's history that has a reminder about itself right on the highway"
:
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/eba7194c-14d6-4658-a622-3e9c767dcc61)

**Comment by bettercalldelta** [comment]
excuse me while i'm going back into your walls

**Comment by VoTheHandsome** [comment]
i don't remember this being in farwood please enlighten me

**Comment by bettercalldelta** [comment]
From 06.04.2023 to 10.04.2023 ruzzians almost invaded Farwood. During the siege, the city was destroyed. There were almost 800 civilian casualties identified during the endless rain of artillery.
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/c8ae6dd3-0e14-4f03-9e29-42442dfd5ef7)
The graveyard was built by locals during the siege.

**Comment by VoTheHandsome** [comment]
HORRIFYING IMAGERY FARWOODER NOOOOOOOOO 😿

**Comment by VoTheHandsome** [comment]
rip to everyone that died

**Comment by bettercalldelta** [comment]
These flags (left to right: Poland, Ukraine, FLASH Division, Chattown's Veterans Battalion, Sigma Division, Chattown, Czechia) now honour the fighters on the arch near the entry to the town.
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/68325d99-6c71-4518-89bc-8fc1599ef04d)

**Comment by bettercalldelta** [comment]
i forgor :skull:

**Comment by bettercalldelta** [comment]
cry about this road
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/d85df613-b9d9-440d-a54e-e2c8a131ad85)

**Comment by VoTheHandsome** [comment]
mfs really decided to use a github issue to chat

**Comment by VoTheHandsome** [comment]
ON THATS IT *cries about it*

**Comment by VoTheHandsome** [comment]
ON

**Comment by VoTheHandsome** [comment]
is this rn or the worst time

**Comment by bettercalldelta** [comment]
Farwood was liberated long ago

**Comment by bettercalldelta** [comment]
On the 11th of April I believe, for I do not remember the exact date.

**Comment by VoTheHandsome** [comment]
Let's go

**Comment by bettercalldelta** [comment]
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/d7226350-6e48-4103-8ee1-8c96b918a6c2)

Yes it was. The majority of the town has been rebuilt since then.

**Comment by bettercalldelta** [comment]
The attached photograph is from April 12th, by the way.

**Comment by bettercalldelta** [comment]
:: Units who fought in Farwood
:flag_ct: NORTH Division
:flag_ct: Chattownian Veterans Battalion
:flag_ct: 1st Chattownian Volunteer Mechanized Brigade
:flag_ct: 3rd Chattownian Volunteer Mechanized Brigade
🇺🇦 FLASH Division
🇺🇦 Sigma Division
🇺🇦 28th Mechanized Brigade of the Armed Forces of Ukraine
🇺🇦 160th Anti-Aircraft Missile Brigade of the Armed Forces of Ukraine

**Comment by bettercalldelta** [comment]
Horrifying failure.

**Comment by bettercalldelta** [comment]
Elaboration on the previously sent message: The failure is with the emoji.

**Comment by bettercalldelta** [comment]
Any way, I hope you caught up on the lore of Leanville, for at this our conversation will conclude. The takeaway is to be decided by you.

**Comment by VoTheHandsome** [comment]
g

**Comment by bettercalldelta** [comment]
I do agree with your statement.

**Comment by VoTheHandsome** [comment]
father in my window

**Comment by bettercalldelta** [comment]
However, I highly recommend you to shed tears about the following attachment:
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/5352c4d3-ac21-4aa3-b7c5-b6ac43e9ee45)

**Comment by VoTheHandsome** [comment]
THE FUCKING TUN

**Comment by VoTheHandsome** [comment]
nel

**Comment by bettercalldelta** [comment]
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/c9e31b2d-8a8a-4b6a-bc6b-a74e7d8e02cb)
Ok.

**Comment by bettercalldelta** [comment]
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/e7cbc181-1190-48f3-b8fd-406a49de261c)
Ok.

**Comment by bettercalldelta** [comment]
I also highly recommend you to shed tears about the following road change in Leanville City:
![зображення](https://github.com/VoTheHandsome/WebbBot/assets/76256620/ae6c3fb8-fdf1-450c-bba8-b8cb996e24b9)
I agree.
Genders in the sky.
I agree.
Children in motion.
I agree.
The chair is not my son.

**Comment by VoTheHandsome** [comment]
i am happy to see the city improve

**Comment by bettercalldelta** [comment]
By the way, would you like to take a guess, which of these parties won the presidential election of the multiverse?

:: Parties represented in the COTR
== Government
[SDP] - Social Democratic Party - center-left, social democracy
[GLC] - Green-Left Coalition - center-left, green politics
== Opposition
[OAM] - One Amendment - far-right, ultraconservatism
[IDR] - Interdimensional Resistance - soft-right, liberalism, liberal conservatism
[PFR] - People's Freedom - right-wing, right-wing populism
[CNP] - Conservative Party - right-wing, conservatism

:: Banned parties
[TRP] - True Patriot - ultra-right, ultranationalism

**Comment by bettercalldelta** [comment]
You would be wrong.

**Comment by bettercalldelta** [comment]
2023 INTERDIMENSIONAL PRESIDENTIAL ELECTION - SECOND ROUND - 100% VOTES COUNTED

59.387% [SDP] Asasieti
40.613% [OAM] Tahermetychnist'

TOTAL NUMBER OF VOTES COUNTED: 897,022,679,351

**Comment by bettercalldelta** [comment]
For further context, here is a quick run-down of the beliefs of Tahermetychnist' and his party.
https://github.com/VoTheHandsome/WebbBot/assets/76256620/8693b4b4-d8a0-4811-a86f-9beb8a1ed136
